[project]
name = "try-flockmtl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.2",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
]
